const KEY='gbbd_admin_v1';
const seedProducts=[{id:'p1',name:'TWS AirBuds Pro',category:'Audio',price:1290,discount:0,stock:20,image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800',description:'Wireless earbuds with charging case',active:true},{id:'p2',name:'Bluetooth Speaker Mini',category:'Audio',price:990,discount:0,stock:15,image:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800',description:'Compact Bluetooth speaker',active:true},{id:'p3',name:'Smart Watch S9',category:'Wearables',price:1850,discount:0,stock:10,image:'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800',description:'Smart wearable watch',active:true}];
let db=load();let page='dashboard';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{products:seedProducts,orders:[],customers:[],categories:['Audio','Wearables','Power & Charging','Mobile Accessories','RGB & Lighting','Home Gadgets','Gaming'],delivery:{dhaka:60,nearby:100,outside:130,nearbyDistricts:'Gazipur, Narayanganj, Narsingdi, Munshiganj, Manikganj'},payments:{cod:true,bkash:true,nagad:true,bkashNumber:'',nagadNumber:''},settings:{store:'Gadget Bazar BD',phone:'',email:'',logo:'',admin:'Administrator'}}}catch(e){return {products:seedProducts,orders:[],customers:[],categories:[],delivery:{dhaka:60,nearby:100,outside:130,nearbyDistricts:''},payments:{cod:true,bkash:true,nagad:true,bkashNumber:'',nagadNumber:''},settings:{store:'Gadget Bazar BD'}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}function $(x){return document.getElementById(x)}
function login(){if($('loginUser').value==='admin'&&$('loginPass').value==='admin123'){$('login').classList.add('hidden');$('app').classList.remove('hidden');render()}else alert('Invalid login')}function logout(){location.reload()}function toggleSide(){document.querySelector('.sidebar').classList.toggle('open')}
function render(){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('pageTitle').textContent=page[0].toUpperCase()+page.slice(1);$('pageSub').textContent=page==='dashboard'?'Store overview':'Manage your store';let html='';if(page==='dashboard')html=dashboard();if(page==='products')html=products();if(page==='orders')html=orders();if(page==='customers')html=customers();if(page==='categories')html=categories();if(page==='delivery')html=delivery();if(page==='payments')html=payments();if(page==='settings')html=settings();$('content').innerHTML=html}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();document.querySelector('.sidebar').classList.remove('open')});
function dashboard(){let sales=db.orders.reduce((a,o)=>a+Number(o.total||0),0),pending=db.orders.filter(o=>o.status==='Pending').length;return `<div class="cards"><div class="card stat"><div><div class="label">Total Products</div><div class="value">${db.products.length}</div></div><div class="ico">▣</div></div><div class="card stat"><div><div class="label">Total Orders</div><div class="value">${db.orders.length}</div></div><div class="ico">▤</div></div><div class="card stat"><div><div class="label">Pending Orders</div><div class="value">${pending}</div></div><div class="ico">◷</div></div><div class="card stat"><div><div class="label">Total Sales</div><div class="value">৳${sales.toLocaleString()}</div></div><div class="ico">৳</div></div></div><div class="grid2"><div class="card"><div class="section-head"><h3>Sales Overview</h3></div><div class="chart">${[32,54,45,70,52,84,64,92,74,60,88,78].map(v=>`<div class="bar" style="height:${v}%"></div>`).join('')}</div></div><div class="card"><div class="section-head"><h3>Recent Orders</h3><button class="btn muted" onclick="page='orders';render()">View all</button></div><div class="mini-list">${db.orders.slice(-5).reverse().map(o=>`<div class="mini-item"><span>${o.orderId||o.id||'Order'}</span><b>৳${Number(o.total||0).toLocaleString()}</b></div>`).join('')||'<div class="empty">No orders yet</div>'}</div></div></div>`}
function products(){return `<div class="section-head"><h3>Products</h3><div class="toolbar"><input class="input" id="psearch" placeholder="Search products..." oninput="filterProducts()"><select class="select" id="stockfilter" onchange="filterProducts()"><option value="all">All stock</option><option value="low">Low stock</option><option value="off">Disabled</option></select><button class="btn primary" onclick="openProduct()">＋ Add Product</button></div></div><div id="productGrid" class="product-grid">${productCards(db.products)}</div>`}
function productCards(arr){if(!arr.length)return '<div class="empty">No products found</div>';return arr.map(p=>`<div class="product-card"><img src="${p.image||'https://placehold.co/800x500?text=Product'}" onerror="this.src='https://placehold.co/800x500?text=Product'"><div class="product-info"><h4>${esc(p.name)} ${p.active?'':'<span class="pill red">Disabled</span>'}</h4><p>${esc(p.category)} · Stock: ${p.stock}</p><div class="price">৳${Number(p.price).toLocaleString()}</div><div class="actions" style="margin-top:10px"><button onclick="openProduct('${p.id}')">Edit</button><button onclick="toggleProduct('${p.id}')">${p.active?'Disable':'Enable'}</button><button onclick="deleteProduct('${p.id}')">Delete</button></div></div></div>`).join('')}
function filterProducts(){let q=($('psearch')?.value||'').toLowerCase(),f=$('stockfilter')?.value||'all';let a=db.products.filter(p=>(p.name+p.category).toLowerCase().includes(q)).filter(p=>f==='all'||(f==='low'&&p.stock<5)||(f==='off'&&!p.active));$('productGrid').innerHTML=productCards(a)}
function openProduct(id=''){
 let p=db.products.find(x=>x.id===id)||{id:'',name:'',category:db.categories[0]||'Audio',price:'',discount:0,stock:0,image:'',description:'',active:true};
 window.editProductImage=p.image||'';
 $('modalTitle').textContent=id?'Edit Product':'Add Product';
 $('modalBody').innerHTML=`<div class="form-grid">
 <label class="full">Product Image<div style="padding:14px;border:1px dashed #315271;border-radius:12px;background:#08182b"><input id="f_image_file" type="file" accept="image/*" onchange="readProductImage(event)"><img id="image_preview" src="${esc(p.image||'')}" style="display:${p.image?'block':'none'};width:100%;height:180px;object-fit:contain;margin-top:10px;border-radius:10px;background:#071426"><small style="display:block;color:#8ea6c1;margin-top:8px">Choose a photo directly from your phone Gallery. Maximum 2.5 MB.</small></div></label>
 <label>Product Name<input id="f_name" value="${esc(p.name)}"></label>
 <label>Category<select id="f_cat">${db.categories.map(c=>`<option ${c===p.category?'selected':''}>${esc(c)}</option>`).join('')}</select></label>
 <label>Price<input id="f_price" type="number" value="${p.price}"></label>
 <label>Discount Price<input id="f_discount" type="number" value="${p.discount||0}"></label>
 <label>Stock Quantity<input id="f_stock" type="number" value="${p.stock}"></label>
 <label class="full">Description<textarea id="f_desc">${esc(p.description||'')}</textarea></label>
 </div><div class="btn-row"><button class="btn muted" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveProduct('${id}')">Save Product</button></div>`;
 $('modal').classList.remove('hidden')
}
function readProductImage(event){
 const file=event.target.files[0]; if(!file)return;
 if(file.size>2.5*1024*1024){alert('Please choose an image under 2.5 MB.');event.target.value='';return;}
 const reader=new FileReader();
 reader.onload=()=>{window.editProductImage=reader.result;const img=$('image_preview');img.src=reader.result;img.style.display='block'};
 reader.readAsDataURL(file);
}
function saveProduct(id){
 let p={id:id||'p_'+Date.now(),name:$('f_name').value.trim(),category:$('f_cat').value,price:Number($('f_price').value||0),discount:Number($('f_discount').value||0),stock:Number($('f_stock').value||0),image:window.editProductImage||'',description:$('f_desc').value.trim(),active:true};
 if(!p.name){alert('Product name is required');return;}
 let i=db.products.findIndex(x=>x.id===p.id);if(i>=0){p.active=db.products[i].active;db.products[i]=p}else db.products.push(p);
 save();closeModal();render()
}
function toggleProduct(id){let p=db.products.find(x=>x.id===id);if(p){p.active=!p.active;save();render()}}function deleteProduct(id){if(confirm('Delete this product?')){db.products=db.products.filter(p=>p.id!==id);save();render()}}
function orders(){let rows=db.orders.map((o,i)=>`<tr><td>${esc(o.orderId||o.id||'#'+(i+1))}</td><td>${esc(o.customer?.name||o.name||'—')}</td><td>${esc(o.customer?.phone||o.phone||'—')}</td><td>৳${Number(o.total||0).toLocaleString()}</td><td>${esc(o.paymentMethod||'COD')}</td><td><span class="pill ${o.status==='Delivered'?'green':o.status==='Cancelled'?'red':o.status==='Pending'?'yellow':'blue'}">${esc(o.status||'Pending')}</span></td><td class="actions"><button onclick="viewOrder(${i})">View</button><button onclick="statusOrder(${i})">Status</button></td></tr>`).join('');return `<div class="section-head"><h3>Orders</h3><div class="toolbar"><input class="input" placeholder="Search order/customer" oninput="searchOrders(this.value)"></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Order ID</th><th>Customer</th><th>Phone</th><th>Total</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody id="orderRows">${rows||'<tr><td colspan="7" class="empty">No orders yet</td></tr>'}</tbody></table></div>`}
function searchOrders(q){q=q.toLowerCase();document.querySelectorAll('#orderRows tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none')}
function viewOrder(i){let o=db.orders[i];$('modalTitle').textContent='Order '+(o.orderId||o.id||'');$('modalBody').innerHTML=`<div class="card"><b>Customer</b><p>${esc(o.customer?.name||o.name||'')} · ${esc(o.customer?.phone||o.phone||'')}</p><p>${esc(o.customer?.district||o.district||'')}, ${esc(o.customer?.upazila||o.area||'')}</p><p>${esc(o.customer?.address||o.address||'')}</p><hr><b>Payment:</b> ${esc(o.paymentMethod||'COD')} ${o.transactionId?' · TXN: '+esc(o.transactionId):''}<p><b>Total:</b> ৳${Number(o.total||0).toLocaleString()}</p><p><b>Note:</b> ${esc(o.note||'—')}</p></div><div class="btn-row"><button class="btn primary" onclick="statusOrder(${i})">Change Status</button></div>`;$('modal').classList.remove('hidden')}
function statusOrder(i){let s=prompt('Status: Pending, Confirmed, Processing, Shipped, Delivered, Cancelled',db.orders[i].status||'Pending');if(['Pending','Confirmed','Processing','Shipped','Delivered','Cancelled'].includes(s)){db.orders[i].status=s;save();closeModal();render()}}
function customers(){let map={};db.orders.forEach(o=>{let n=o.customer?.name||o.name||'Unknown';map[n]??={name:n,phone:o.customer?.phone||o.phone||'',orders:0,spent:0};map[n].orders++;map[n].spent+=Number(o.total||0)});return `<div class="section-head"><h3>Customers</h3></div><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Phone</th><th>Orders</th><th>Total Spent</th></tr></thead><tbody>${Object.values(map).map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${c.orders}</td><td>৳${c.spent.toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No customers yet</td></tr>'}</tbody></table></div>`}
function categories(){return `<div class="grid2"><div class="card"><div class="section-head"><h3>Categories</h3><button class="btn primary" onclick="addCategory()">＋ Add</button></div><div class="mini-list">${db.categories.map((c,i)=>`<div class="mini-item"><span>${esc(c)}</span><span><button class="btn muted" onclick="renameCategory(${i})">Edit</button> <button class="btn danger" onclick="deleteCategory(${i})">Delete</button></span></div>`).join('')}</div></div><div class="card"><h3>Category Control</h3><p class="label">Products are grouped by these categories. Renaming a category can be done here.</p></div></div>`}
function addCategory(){let c=prompt('Category name');if(c&&c.trim()&&!db.categories.includes(c.trim())){db.categories.push(c.trim());save();render()}}function renameCategory(i){let c=prompt('New name',db.categories[i]);if(c&&c.trim()){db.products.forEach(p=>{if(p.category===db.categories[i])p.category=c.trim()});db.categories[i]=c.trim();save();render()}}function deleteCategory(i){if(confirm('Delete category?')){db.categories.splice(i,1);save();render()}}
function delivery(){return `<div class="card"><div class="section-head"><h3>Delivery Settings</h3></div><div class="form-grid"><label>Dhaka City Fee<input id="d_dhaka" type="number" value="${db.delivery.dhaka}"></label><label>Nearby Dhaka Fee<input id="d_nearby" type="number" value="${db.delivery.nearby}"></label><label>Outside Dhaka Fee<input id="d_outside" type="number" value="${db.delivery.outside}"></label><label class="full">Nearby Districts (comma separated)<input id="d_dist" value="${esc(db.delivery.nearbyDistricts)}"></label></div><div class="btn-row"><button class="btn primary" onclick="saveDelivery()">Save Delivery Settings</button></div></div>`}function saveDelivery(){db.delivery={dhaka:Number($('d_dhaka').value),nearby:Number($('d_nearby').value),outside:Number($('d_outside').value),nearbyDistricts:$('d_dist').value};save();alert('Saved');render()}
function payments(){return `<div class="card"><div class="form-grid"><label>Cash on Delivery<select id="pay_cod"><option value="true" ${db.payments.cod?'selected':''}>Enabled</option><option value="false" ${!db.payments.cod?'selected':''}>Disabled</option></select></label><label>bKash<select id="pay_bk"><option value="true" ${db.payments.bkash?'selected':''}>Enabled</option><option value="false" ${!db.payments.bkash?'selected':''}>Disabled</option></select></label><label>Nagad<select id="pay_ng"><option value="true" ${db.payments.nagad?'selected':''}>Enabled</option><option value="false" ${!db.payments.nagad?'selected':''}>Disabled</option></select></label><label>bKash Number<input id="pay_bn" value="${esc(db.payments.bkashNumber||'')}"></label><label>Nagad Number<input id="pay_nn" value="${esc(db.payments.nagadNumber||'')}"></label></div><div class="btn-row"><button class="btn primary" onclick="savePayments()">Save Payment Settings</button></div></div>`}function savePayments(){db.payments={cod:$('pay_cod').value==='true',bkash:$('pay_bk').value==='true',nagad:$('pay_ng').value==='true',bkashNumber:$('pay_bn').value,nagadNumber:$('pay_nn').value};save();alert('Saved');render()}
function settings(){return `<div class="card"><div class="form-grid"><label>Store Name<input id="s_store" value="${esc(db.settings.store||'Gadget Bazar BD')}"></label><label>Admin Name<input id="s_admin" value="${esc(db.settings.admin||'Administrator')}"></label><label>Phone<input id="s_phone" value="${esc(db.settings.phone||'')}"></label><label>Email<input id="s_email" value="${esc(db.settings.email||'')}"></label><label class="full">Logo URL<input id="s_logo" value="${esc(db.settings.logo||'')}"></label></div><div class="btn-row"><button class="btn primary" onclick="saveSettings()">Save Settings</button></div></div><div class="card" style="margin-top:16px"><h3>Data & Connection</h3><p class="label">This version is a standalone admin prototype using browser storage. It does not yet sync live changes to the public customer website.</p></div>`}function saveSettings(){db.settings={store:$('s_store').value,admin:$('s_admin').value,phone:$('s_phone').value,email:$('s_email').value,logo:$('s_logo').value};save();alert('Saved');render()}
function closeModal(){$('modal').classList.add('hidden')}function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='gadget-bazar-admin-data.json';a.click()}$('importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();render();alert('Imported')}catch(x){alert('Invalid data')}};r.readAsText(f)};
render();
