const APPS_SCRIPT_URL="PASTE_YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL_HERE";
const products=[
{id:1,n:"TWS AirBuds Pro",c:"Audio",p:1290,e:"🎧",a:true},{id:2,n:"Bluetooth Speaker Mini",c:"Audio",p:990,e:"🔊",a:true},{id:3,n:"Smart Watch S9",c:"Wearables",p:1850,e:"⌚",a:true},{id:4,n:"Fitness Smart Band",c:"Wearables",p:850,e:"⌚",a:false},{id:5,n:"Power Bank 10000mAh",c:"Power & Charging",p:1190,e:"🔋",a:true},{id:6,n:"20W Fast Charger",c:"Power & Charging",p:690,e:"🔌",a:true},{id:7,n:"Fast Charge Type-C Cable",c:"Power & Charging",p:290,e:"🔗",a:false},{id:8,n:"360° Phone Stand",c:"Mobile Accessories",p:350,e:"📱",a:true},{id:9,n:"Wireless Mouse",c:"Mobile Accessories",p:590,e:"🖱️",a:true},{id:10,n:"RGB Strip Light 5M",c:"RGB & Lighting",p:890,e:"🌈",a:true},{id:11,n:"RGB Desk Lamp",c:"RGB & Lighting",p:1250,e:"💡",a:false},{id:12,n:"Smart LED Night Light",c:"Home Gadgets",p:650,e:"🏠",a:true},{id:13,n:"Mini Rechargeable Fan",c:"Home Gadgets",p:780,e:"🌀",a:true},{id:14,n:"Gaming Earphones",c:"Gaming",p:720,e:"🎮",a:true},{id:15,n:"RGB Gaming Mouse Pad",c:"Gaming",p:990,e:"🖥️",a:false}];
let st={status:"all",cat:"all",search:"",sort:"featured",cart:JSON.parse(localStorage.gbCart||"[]")};
const $=x=>document.querySelector(x),fmt=n=>new Intl.NumberFormat("en-BD").format(n),save=()=>localStorage.gbCart=JSON.stringify(st.cart);
function list(){let x=products.filter(p=>(st.status==="all"||(st.status==="available"&&p.a)||(st.status==="out"&&!p.a))&&(st.cat==="all"||p.c===st.cat)&&(!st.search||(p.n+" "+p.c).toLowerCase().includes(st.search.toLowerCase())));if(st.sort==="low")x.sort((a,b)=>a.p-b.p);if(st.sort==="high")x.sort((a,b)=>b.p-a.p);if(st.sort==="name")x.sort((a,b)=>a.n.localeCompare(b.n));return x}
function render(){let x=list(),box=$("#catalog");box.innerHTML="";$("#empty").classList.toggle("hide",x.length>0);x.forEach(p=>{let d=document.createElement("article");d.className="card";d.innerHTML=`<div class="pic">${p.e}</div><span class="badge ${p.a?"":"out"}">${p.a?"AVAILABLE":"OUT OF STOCK"}</span><div class="body"><div class="muted">${p.c}</div><b>${p.n}</b><div class="price">৳${fmt(p.p)}</div><button class="add" ${p.a?"":"disabled"} data-add="${p.id}">${p.a?"Add to Cart":"Out of Stock"}</button></div>`;box.appendChild(d)});document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(+b.dataset.add));document.querySelectorAll(".status").forEach(b=>b.classList.toggle("active",b.dataset.status===st.status));renderCart()}
function add(id){let i=st.cart.find(x=>x.id===id);i?i.q++:st.cart.push({id,q:1});save();render();$("#cart").classList.remove("hide")}
function chg(id,n){let i=st.cart.find(x=>x.id===id);if(!i)return;i.q+=n;if(i.q<1)st.cart=st.cart.filter(x=>x.id!==id);save();render()}
function totals(){let sub=st.cart.reduce((s,i)=>{let p=products.find(x=>x.id===i.id);return s+(p?p.p*i.q:0)},0);return{sub,del:sub?(sub>=2000?0:80):0,total:sub+(sub?(sub>=2000?0:80):0)}}
function renderCart(){let box=$("#cartItems"),t=totals();box.innerHTML=st.cart.length?st.cart.map(i=>{let p=products.find(x=>x.id===i.id);return`<div class="line"><span>${p.n}<br><small>৳${fmt(p.p)} × ${i.q}</small></span><span><button onclick="chg(${i.id},1)">+</button> <button onclick="chg(${i.id},-1)">−</button></span></div>`}).join(""):"<p>Your cart is empty.</p>";$("#cartCount").textContent=st.cart.reduce((s,i)=>s+i.q,0);$("#total").textContent=fmt(t.total);}
function closeDrawer(){$("#drawer").classList.remove("open");$("#shade").classList.add("hide")}
function summary(){let t=totals();$("#summary").innerHTML=st.cart.map(i=>{let p=products.find(x=>x.id===i.id);return`<div>${p.n} × ${i.q} — ৳${fmt(p.p*i.q)}</div>`}).join("")+`<hr><b>Total: ৳${fmt(t.total)}</b>`}
$("#menuBtn").onclick=()=>{$("#drawer").classList.add("open");$("#shade").classList.remove("hide")};$("#closeMenu").onclick=closeDrawer;$("#shade").onclick=closeDrawer;
document.querySelectorAll("[data-menu]").forEach(b=>b.onclick=()=>{st.status=b.dataset.menu;st.cat="all";closeDrawer();render();location.hash="products"});document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{st.cat=b.dataset.cat;st.status="all";closeDrawer();render();location.hash="products"});document.querySelectorAll(".status").forEach(b=>b.onclick=()=>{st.status=b.dataset.status;st.cat="all";render()});
$("#search").oninput=e=>{st.search=e.target.value;render()};$("#sort").onchange=e=>{st.sort=e.target.value;render()};$("#cartBtn").onclick=()=>$("#cart").classList.remove("hide");$("#closeCart").onclick=()=>$("#cart").classList.add("hide");$("#checkout").onclick=()=>{if(!st.cart.length)return alert("Your cart is empty.");$("#cart").classList.add("hide");summary();$("#checkoutModal").classList.remove("hide")};$("#closeCheckout").onclick=()=>$("#checkoutModal").classList.add("hide");$("#done").onclick=()=>$("#success").classList.add("hide");$("#payment").onchange=e=>$("#trxBox").classList.toggle("hide",e.target.value==="Cash on Delivery");
$("#orderForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),t=totals(),order={orderId:"GBBD-"+Date.now().toString().slice(-8),createdAt:new Date().toISOString(),customer:{name:f.get("name"),phone:f.get("phone"),district:f.get("district"),area:f.get("area"),address:f.get("address")},paymentMethod:f.get("payment"),transactionId:f.get("transactionId")||"",note:f.get("note")||"",items:st.cart,subtotal:t.sub,delivery:t.del,total:t.total};try{if(!APPS_SCRIPT_URL.includes("PASTE_YOUR")){await fetch(APPS_SCRIPT_URL,{method:"POST",mode:"no-cors",body:JSON.stringify(order)});}else{localStorage.gbLastOrder=JSON.stringify(order)}st.cart=[];save();renderCart();e.target.reset();$("#trxBox").classList.add("hide");$("#orderId").textContent=order.orderId;$("#checkoutModal").classList.add("hide");$("#success").classList.remove("hide")}catch(err){alert("Order submission failed. Please try again.")}};
render();
