const products=[
{id:1,n:"TWS AirBuds Pro",c:"Audio",p:1290,e:"🎧",a:true},{id:2,n:"Bluetooth Speaker Mini",c:"Audio",p:990,e:"🔊",a:true},
{id:3,n:"Smart Watch S9",c:"Wearables",p:1850,e:"⌚",a:true},{id:4,n:"Fitness Smart Band",c:"Wearables",p:850,e:"⌚",a:false},
{id:5,n:"Power Bank 10000mAh",c:"Power & Charging",p:1190,e:"🔋",a:true},{id:6,n:"20W Fast Charger",c:"Power & Charging",p:690,e:"🔌",a:true},
{id:7,n:"Fast Charge Type-C Cable",c:"Power & Charging",p:290,e:"🔗",a:false},{id:8,n:"360° Phone Stand",c:"Mobile Accessories",p:350,e:"📱",a:true},
{id:9,n:"Wireless Mouse",c:"Mobile Accessories",p:590,e:"🖱️",a:true},{id:10,n:"RGB Strip Light 5M",c:"RGB & Lighting",p:890,e:"🌈",a:true},
{id:11,n:"RGB Desk Lamp",c:"RGB & Lighting",p:1250,e:"💡",a:false},{id:12,n:"Smart LED Night Light",c:"Home Gadgets",p:650,e:"🏠",a:true},
{id:13,n:"Mini Rechargeable Fan",c:"Home Gadgets",p:780,e:"🌀",a:true},{id:14,n:"Gaming Earphones",c:"Gaming",p:720,e:"🎮",a:true},
{id:15,n:"RGB Gaming Mouse Pad",c:"Gaming",p:990,e:"🖥️",a:false}];
let st={status:"all",cat:"all",search:"",sort:"featured",cart:JSON.parse(localStorage.gbCart||"[]")};
const $=x=>document.querySelector(x),fmt=n=>new Intl.NumberFormat("en-BD").format(n);
function list(){let x=products.filter(p=>(st.status=="all"||(st.status=="available"&&p.a)||(st.status=="out"&&!p.a))&&(st.cat=="all"||p.c==st.cat)&&(!st.search||(p.n+" "+p.c).toLowerCase().includes(st.search.toLowerCase())));if(st.sort=="low")x.sort((a,b)=>a.p-b.p);if(st.sort=="high")x.sort((a,b)=>b.p-a.p);if(st.sort=="name")x.sort((a,b)=>a.n.localeCompare(b.n));return x}
function render(){let box=$("#catalog"),x=list();box.innerHTML="";$("#empty").classList.toggle("hide",x.length>0);x.forEach(p=>{let d=document.createElement("article");d.className="card";d.innerHTML=`<div class="pic">${p.e}</div><span class="badge ${p.a?"":"out"}">${p.a?"AVAILABLE":"OUT OF STOCK"}</span><div class="body"><div class="muted">${p.c}</div><b>${p.n}</b><div class="price">৳${fmt(p.p)}</div><button class="add" ${p.a?"":"disabled"} data-add="${p.id}">${p.a?"Add to Cart":"Out of Stock"}</button></div>`;box.appendChild(d)});document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(+b.dataset.add));document.querySelectorAll(".status").forEach(b=>b.classList.toggle("active",b.dataset.status==st.status));renderCart()}
function add(id){let i=st.cart.find(x=>x.id==id);i?i.q++:st.cart.push({id,q:1});save();render()}function save(){localStorage.gbCart=JSON.stringify(st.cart)}
function renderCart(){let count=st.cart.reduce((s,x)=>s+x.q,0);$("#cartCount").textContent=count;let box=$("#cartItems"),total=0;box.innerHTML="";st.cart.forEach(i=>{let p=products.find(x=>x.id==i.id);if(!p)return;total+=p.p*i.q;let d=document.createElement("div");d.className="line";d.innerHTML=`<span>${p.n}<br><small>৳${fmt(p.p)} × ${i.q}</small></span><span><button data-q="${p.id}" data-d="1">+</button> <button data-q="${p.id}" data-d="-1">−</button></span>`;box.appendChild(d)});$("#total").textContent=fmt(total);document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>chg(+b.dataset.q,+b.dataset.d))}
function chg(id,n){let i=st.cart.find(x=>x.id==id);if(!i)return;i.q+=n;if(i.q<1)st.cart=st.cart.filter(x=>x.id!=id);save();render()}
document.querySelectorAll(".status").forEach(b=>b.onclick=()=>{st.status=b.dataset.status;render()});document.querySelectorAll(".cats button").forEach(b=>b.onclick=()=>{st.cat=b.dataset.cat;location.hash="products";render()});$("#sort").onchange=e=>{st.sort=e.target.value;render()};$("#searchBtn").onclick=()=>$("#searchWrap").classList.toggle("hide");$("#search").oninput=e=>{st.search=e.target.value;render()};$("#cartBtn").onclick=()=>$("#cart").classList.remove("hide");$("#closeCart").onclick=()=>$("#cart").classList.add("hide");$("#checkout").onclick=()=>alert("Demo COD checkout. Real order backend will be added before launch.");render();